name: Sync with template

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v1.1.0
        with:
          source_repo: "https://github.com/BIOM421/Lesson1-GitHub-Python"
          source_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
